apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform applications

  sourceRepos:
    - https://github.com/apurvbidkar22/*
    - https://github.com/apurvbidkar22/test-argo.git
    - https://git.aitglobalindia.com/ait-inhouse1/nira-website.git
    - https://git.aitglobalindia.com/nira_hrms/niraxo-admin.git
    - https://git.aitglobalindia.com/nira_hrms/niraxo_microservices.git

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

