apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/apurvbidkar22/test-project.git
    targetRevision: main
    path: targets/dev/app1   # can be empty

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy: {}   # 👈 NO auto-sync

