apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/apurvbidkar22/test-project.git
    targetRevision: main
    path: overlays/$(ENV)
    namespace: test-app-$(ENV)
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-ENV
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

